apiVersion: v1  
kind: ServiceAccount  
metadata:  
  name: loadtest

---

apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRole  
metadata:  
  name: loadtest-reader
rules:  
- apiGroups: [""]  
  resources: ["pods", "pods/log"]  
  verbs: ["get", "list", "watch"]  
  
---  
  
apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRoleBinding  
metadata:  
  name: loadtest-reader-binding  
subjects:  
- kind: ServiceAccount  
  name: loadtest  
  namespace: default  
roleRef:  
  kind: ClusterRole  
  name: loadtest-reader  
  apiGroup: rbac.authorization.k8s.io  
